### ISSUE TITLE
Errors running blueprint on fresh Laravel + Sail + Jetstream setup

### ISSUE THREAD

**Issue by KimLangholz** [laravel-shift/blueprint#410] opened 2021-01-14 10:29 UTC
- Laravel Version: 8.22.1
- PHP Version: 8.0.0
- Blueprint Version: 1.20.1
- Platform: Linux (WSL2)
- Sail: 1.1.0
- Jetstream: 2.1.0

### Issue:

When running 
``` 
sail artisan blueprint:build
```
I get the following error:

`[2021-01-13 13:33:15] local.ERROR: Call to a member function columns() on null {"exception":"[object] (Error(code: 0): Call to a member function columns() on null at /var/www/html/vendor/laravel-shift/blueprint/src/Generators/TestGenerator.php:251)
[stacktrace]
#0 /var/www/html/vendor/laravel-shift/blueprint/src/Generators/TestGenerator.php(89): Blueprint\\Generators\\TestGenerator->buildTestCases()
#1 /var/www/html/vendor/laravel-shift/blueprint/src/Generators/TestGenerator.php(64): Blueprint\\Generators\\TestGenerator->populateStub()
#2 /var/www/html/vendor/laravel-shift/blueprint/src/Blueprint.php(85): Blueprint\\Generators\\TestGenerator->output()
#3 /var/www/html/vendor/laravel-shift/blueprint/src/Builder.php(26): Blueprint\\Blueprint->generate()
#4 /var/www/html/vendor/laravel-shift/blueprint/src/Commands/BuildCommand.php(65): Blueprint\\Builder->execute()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Blueprint\\Commands\\BuildCommand->handle()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\\Container\\BoundMethod::call()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#11 /var/www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#13 /var/www/html/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run()
#14 /var/www/html/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand()
#15 /var/www/html/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#18 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#19 {main}
"} `

It builds the controllers and models, but not the views/tests. 

When then trying to run the erase
```
sail artisan blueprint:erase
```
I get the following error:

`[2021-01-13 13:33:34] local.ERROR: File does not exist at path .blueprint. {"exception":"[object] (Illuminate\\Contracts\\Filesystem\\FileNotFoundException(code: 0): File does not exist at path .blueprint. at /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:57)
[stacktrace]
#0 /var/www/html/vendor/laravel-shift/blueprint/src/Commands/EraseCommand.php(47): Illuminate\\Filesystem\\Filesystem->get()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Blueprint\\Commands\\EraseCommand->handle()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\\Container\\BoundMethod::call()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#7 /var/www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#9 /var/www/html/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run()
#10 /var/www/html/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand()
#11 /var/www/html/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#14 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#15 {main}
"} `

I've tried it on another fresh Laravel/Sail/Jetstream install as well with same result. 

### draft.yaml:
```
models:
  Category:
    category_id: id 
    category: string
    timestamps: false
  
  Role:
    role_id: id
    role: string
    timestamps: false
  
  Person:
    person_id: id
    profile_image_path: string nullable
    name: string
    is_female: boolean
    is_actor: boolean
    is_dead: boolean
    birthdate: datetime nullable
    deathdate: datetime nullable
    burial_place: string nullable
    nationality: string nullable
    city: string nullable
    country: string nullable
    education: string nullable
    short_intro: longtext nullable
    biography: longtext nullable
    birth_city: string nullable
    birth_country: string nullable
    timestamps: false
  
  Relation:
    relation_id: id
    person_id: id
    relation: string
    related_person_id: id foreign:person
    timestamps: false
  
  Starsign:
    starsign_id: id
    name: string
    description: longtext nullable
    from_date: datetime
    to_date: datetime
    timestamps: false
  
  Movie:
    movie_id: id
    title: string
    publishing_date: datetime nullable
    cover: string nullable
    category_id: id
    timestamp: false
  
  Characters:
    character_id: id
    name: string
    timestamp: false
  
  MovieCharacter:
    movie_character_id: id
    character_id: id
    movie_id: id
    role_part: string nullable
    picture: string nullable
    timestamp: false
  
  MovieProduction:
    movie_production_id: id
    person_id: id
    role_id: id
    movie_character_id: id
    timestamp: false
  
  TvSeries:
    tv_series_id: id
    title: string
    publishing_date: datetime nullable
    cover: string nullable
    category_id: id
    seasons: integer nullable
    timestamp: false

  TvSeriesEpisode:
    tv_series_episode_id: id
    tv_series_id: id
    episode_number: integer nullable
    title: string
    publishing_date: datetime nullable
    cover: string nullable
    season: integer nullable
    timestamp: false


  TvSeriesCharacters:
    tv_series_characters_id: id
    character_id: id
    tv_series_id: id
    picture: string nullable
    role_part: string nullable
    timestamp: false

  TvSeriesProduction:
    tv_series_production_id: id
    tv_series_episode_id: id
    person_id: id
    role_id: id
    tv_series_character_id: id
    timestamp: false

controllers:
  Movie:
    resource

  TvSeries:
    resource
  
  Episode:
    resource
  
  Character:
    resource
  
  Category:
    resource

  Role:
    resource

  Person:
    resource

  Relation:
    resource
  
```
Am I doing something wrong?

**Comment by nathane** [comment] 2021-01-15 00:53
@KimLangholz You mentioned using `Laravel Version: 4.1.1`. Blueprint currently requires an application running Laravel version 6.0 or higher.  Is that the issue?

**Comment by KimLangholz** [comment] 2021-01-15 10:10
Sorry. Must have been drinking. :S Running 8.22.1. Just confirmed that the other versions I've listed is correct.

**Comment by jasonmccreary** [comment] 2021-01-15 13:42
@KimLangholz this sounds to me like a model reference is missing. Have you tried running `blueprint:trace` then running `blueprint:build`?

**Comment by ugurcanb** [comment] 2021-01-23 01:48
can it be 
`        return config('blueprint.namespace').'\\'.($sub_namespace ? $sub_namespace.'\\' : '').$model_name;
`
on line 220 in \Blueprint\Generators\ControllerGenerator -> fullyQualifyModelReference()  method? 

I was getting the same and changed it to  
`        return config('blueprint.namespace') . '\\' . (config('blueprint.models_namespace') ? config('blueprint.models_namespace') . '\\' : '') . ($sub_namespace ? $sub_namespace . '\\' : '') . ucfirst($model_name);
`  alongside with other things but i think that is the one.

**Comment by jasonmccreary** [comment] 2021-01-23 15:00
@ugurcanb, if you can demonstrate this with a failing test, go ahead and implement the change in a PR. 👍 

Otherwise, I'll try to take a look next week.

**Comment by kpruhs** [comment] 2021-02-09 02:58
FWIW:  I have been having this problem and seem to have "fixed" it. The error I'm getting points to line 251 of TestGenerator.php (vendor/laravel-shift/blueprint/src/Generators/TestGenerator.php).

I believe it is due to the lack of specifying a condition on else. The if checks to see if the $local_model var is not null, plus another condition. The else condition essentially tries to process anything that doesnt meet the if condition, including trying to run a foreach on the $local_model var even if it is null. 

This fix works for me--replace the else on line 250 with an else if:
`} else if (!is_null($local_model))  {`

I'm not familiar enough with the code base yet to know if this is the correct fix. However it does allow the build process to complete and create all the files.

**Comment by jasonmccreary** [comment] 2021-02-09 14:52
I'll try to take a look at this later in the week. But if it fixes your issue and doesn't break any other tests, go ahead and open a PR for it.

**Comment by KimLangholz** [comment] 2021-02-09 19:39
After running 'blueprint:trace' I got: "Traced 14 models" which matches the number of models I am trying to build. 

Running 'blueprint:build' afterwards got me no further than initially.

**Comment by justin713** [comment] 2021-02-22 20:38
@kpruhs: I tried your `else if` in the same place and also got all the way through the `blueprint:build` command. However, I think it might be related to a bad reference in `drafts.yaml` which caused `$local_model->hasColumn` to fail.

I'll defer to those that know much more, but wouldn't it be preferred to have this check fail and throw an error with contextual information on which definitions in `drafts.yaml` might be the cause? If `$column` doesn't exist, it might save some headaches later.

**Comment by nathane** [comment] 2021-02-23 19:19
Hey @KimLangholz,

Sorry for the late reply, I've been very busy.

1. In your draft file you defined `Episode` resource **controller** but you did not define an `Episode` **model**.
2. In your draft file you defined `Character` resource **controller** but you did not define a `Character` **model**.

Because these Models were not defined blueprint returns `null` and calling `->columns()` on null is causing these errors.

Hope that helps, happy coding!

**Comment by nathane** [comment] 2021-03-04 19:43
Hey @jasonmccreary, feel to close this issue, it has been resolved.

**Closed** 2021-03-04 23:58 UTC
Labels: bug, pending
